remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Black 4 Battery
logo: /assets/img/logo.png
description: Keep running your app, save battery on unused screen area.

show_downloads: false
google_analytics: false

github:
    is_user_page: false
    is_project_page: false